


# Part 2 : Model-Training & CNN Test

## Importing Libraries

In [ ]:
# Importing Libraries
import pandas as pd
import numpy as np
import pickle

In [ ]:
# df_train=pd.read_csv('train_final.csv',index_col=False)
# labels=df_train[['2025']]

In [ ]:
# df_train.drop(df_train.columns[[45*45]],axis=1,inplace=True)
# df_train.head(10)

0    1    2    3    4    5    6    7    8    9  ...  2015  2016  2017  \
0    0    0    0    0    0    0    0    0    0    0  ...     0     0     0   
1    0    0    0    0    0    0    0    0    0    0  ...     0     0     0   
2    0    0    0    0    0    0    0    0    0    0  ...     0     0     0   
3  255  255  255  255  255  255  255  255  255  255  ...     0     0     0   
4    0    0    0    0    0    0    0    0    0    0  ...     0     0     0   
5    0    0    0    0    0    0    0    0    0    0  ...     0   145   255   
6    0    0    0    0    0    0    0    0    0    0  ...     0     0     0   
7    0    0    0    0    0    0    0    0    0    0  ...     0     0     0   
8  255  255  255  255  255  255  255  255  255  255  ...     0     0     0   
9    0    0    0    0    0    0    0    0    0    0  ...     0     0     0   

   2018  2019  2020  2021  2022  2023  2024  
0     0     0     0     0     0     0     0  
1     0     0     0     0     0     0     0  
2     0     0     0     0     0     0     0  
3     0     0     0     0     0     0     0  
4     0     0     0     0     0     0     0  
5   145     0     0     0     0     0     0  
6     0     0     0     0     0     0     0  
7     0     0     0     0     0     0     0  
8     0     0     0     0     0     0     0  
9     0     0     0     0     0     0     0  

[10 rows x 2025 columns]

In [4]:
np.random.seed(1212)
import keras
from keras.models import Model
from keras.layers import *
from keras import optimizers
from keras.layers import Input, Dense
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout
from keras.layers import Flatten
from keras.layers import Conv2D, MaxPooling2D
from keras.utils import to_categorical

from keras import backend as K
# K.image_data_format()

In [ ]:
# labels=np.array(labels)
# labels

array([[10],
       [ 1],
       [10],
       ...,
       [ 1],
       [ 3],
       [ 2]])

In [ ]:

# cat=to_categorical(labels,num_classes=13)

In [ ]:
# print(cat)

[[0. 0. 0. ... 1. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 ...
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]]


In [ ]:
# df_train.head(10)

0    1    2    3    4    5    6    7    8    9  ...  2015  2016  2017  \
0    0    0    0    0    0    0    0    0    0    0  ...     0     0     0   
1    0    0    0    0    0    0    0    0    0    0  ...     0     0     0   
2    0    0    0    0    0    0    0    0    0    0  ...     0     0     0   
3  255  255  255  255  255  255  255  255  255  255  ...     0     0     0   
4    0    0    0    0    0    0    0    0    0    0  ...     0     0     0   
5    0    0    0    0    0    0    0    0    0    0  ...     0   145   255   
6    0    0    0    0    0    0    0    0    0    0  ...     0     0     0   
7    0    0    0    0    0    0    0    0    0    0  ...     0     0     0   
8  255  255  255  255  255  255  255  255  255  255  ...     0     0     0   
9    0    0    0    0    0    0    0    0    0    0  ...     0     0     0   

   2018  2019  2020  2021  2022  2023  2024  
0     0     0     0     0     0     0     0  
1     0     0     0     0     0     0     0  
2     0     0     0     0     0     0     0  
3     0     0     0     0     0     0     0  
4     0     0     0     0     0     0     0  
5   145     0     0     0     0     0     0  
6     0     0     0     0     0     0     0  
7     0     0     0     0     0     0     0  
8     0     0     0     0     0     0     0  
9     0     0     0     0     0     0     0  

[10 rows x 2025 columns]

In [ ]:
# df_train.shape

(206881, 2025)

In [ ]:
# temp=df_train.to_numpy()

In [ ]:
# X_train = temp.reshape(temp.shape[0], 45, 45, 1)

In [ ]:
# temp.shape[0]

206881

In [ ]:
# X_train.shape

(206881, 45, 45, 1)

In [ ]:
# l=[]
# for i in range(df_train.shape[0]):
#     l.append(np.array(df_train[i:i+1]).reshape(1,45,45))

In [ ]:
# np.random.seed(7)

In [ ]:
# X_train.shape

(206881, 45, 45, 1)

## Building the CNN model

In [ ]:
# model = Sequential()
# model.add(Conv2D(32, (3,3), input_shape=(45,45,1), activation='relu',padding='same'))
# model.add(MaxPooling2D(pool_size=(2, 2)))
# model.add(Conv2D(15, (3, 3), activation='relu'))
# model.add(MaxPooling2D(pool_size=(2, 2)))
# model.add(Dropout(0.2))
# model.add(Flatten())
# model.add(Dense(128, activation='relu'))
# model.add(Dense(50, activation='relu'))
# model.add(Dense(13, activation='softmax'))

c:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [ ]:
# Compile model
# model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

## Training the model

In [ ]:
# from keras.models import model_from_json

In [ ]:
# model.fit(X_train, cat, epochs=10, batch_size=200,shuffle=True,verbose=1)

Epoch 1/10
1035/1035 ━━━━━━━━━━━━━━━━━━━━ 53s 50ms/step - accuracy: 0.8942 - loss: 0.7664
Epoch 2/10
1035/1035 ━━━━━━━━━━━━━━━━━━━━ 48s 46ms/step - accuracy: 0.9914 - loss: 0.0310
Epoch 3/10
1035/1035 ━━━━━━━━━━━━━━━━━━━━ 46s 44ms/step - accuracy: 0.9943 - loss: 0.0196
Epoch 4/10
1035/1035 ━━━━━━━━━━━━━━━━━━━━ 49s 47ms/step - accuracy: 0.9955 - loss: 0.0149
Epoch 5/10
1035/1035 ━━━━━━━━━━━━━━━━━━━━ 54s 52ms/step - accuracy: 0.9966 - loss: 0.0120
Epoch 6/10
1035/1035 ━━━━━━━━━━━━━━━━━━━━ 54s 52ms/step - accuracy: 0.9968 - loss: 0.0111
Epoch 7/10
1035/1035 ━━━━━━━━━━━━━━━━━━━━ 52s 50ms/step - accuracy: 0.9973 - loss: 0.0099
Epoch 8/10
1035/1035 ━━━━━━━━━━━━━━━━━━━━ 58s 56ms/step - accuracy: 0.9978 - loss: 0.0077
Epoch 9/10
1035/1035 ━━━━━━━━━━━━━━━━━━━━ 58s 56ms/step - accuracy: 0.9980 - loss: 0.0068
Epoch 10/10
1035/1035 ━━━━━━━━━━━━━━━━━━━━ 57s 55ms/step - accuracy: 0.9974 - loss: 0.0089


In [ ]:
# model_json = model.to_json()
# with open("model_final.json", "w") as json_file:
#     json_file.write(model_json)
# # # serialize weights to HDF5
# model.save_weights("model_final.weights.h5")


In [22]:
import cv2
import numpy
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout
from keras.layers import Flatten
from keras.layers import Conv2D,MaxPooling2D 
from keras import backend as K
# K.set_image_dim_ordering('th')
from keras.models import model_from_json

In [23]:
json_file = open('model_final.json', 'r')
loaded_model_json = json_file.read()
json_file.close()
loaded_model = model_from_json(loaded_model_json)
# load weights into new model
loaded_model.load_weights("model_final.weights.h5")

In [32]:
import cv2
import numpy as np
img = cv2.imread(r'D:\handwritting_equation\Untitled.png',cv2.IMREAD_GRAYSCALE)

In [33]:
img

array([[255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       ...,
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255]], dtype=uint8)

In [34]:
if img is not None:
    img = ~img  # Đảo màu
    ret, thresh = cv2.threshold(img, 127, 255, cv2.THRESH_BINARY)
    
    # Tìm contours của các chữ số trong ảnh
    ctrs, _ = cv2.findContours(thresh, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)
    
    # Sắp xếp contours theo vị trí từ trái sang phải
    cnt = sorted(ctrs, key=lambda ctr: cv2.boundingRect(ctr)[0])
    
    train_data = []
    rects = [cv2.boundingRect(c) for c in cnt]  # Lưu danh sách (x, y, w, h)
    
    final_rect = []
    for r in rects:
        x, y, w, h = r
        if w * h > 40:  # Bỏ qua các vùng quá nhỏ (nhiễu)
            final_rect.append(r)
    
    for r in final_rect:
        x, y, w, h = r
        im_crop = thresh[y:y+h, x:x+w]  # Crop chính xác ký tự
        padding = 10
        im_crop = thresh[max(0, y-padding):min(y+h+padding, thresh.shape[0]),
                        max(0, x-padding):min(x+w+padding, thresh.shape[1])]

        # Chuẩn hóa kích thước ảnh về (28, 28)
        im_resize = cv2.resize(im_crop, (45, 45), interpolation=cv2.INTER_AREA)
        # im_resize = np.reshape(im_resize, (45, 45, 1))  # Chuyển thành dạng tensor
    
        train_data.append(im_resize)    

    # train_data = []
    # for c in cnt:

    # rects = [cv2.boundingRect(c) for c in cnt]  # Lưu danh sách (x, y, w, h)
    
    # final_rect = []
    # for c in cnt:
    #     x, y, w, h = r
    #     # if w * h > 1:  # Bỏ qua các vùng quá nhỏ (nhiễu)
    #     final_rect.append(r)
    
    # for r in final_rect:
    #     x, y, w, h = r
    #     im_crop = thresh[y:y+h, x:x+w]  # Crop chính xác ký tự
        
    #     # Chuẩn hóa kích thước ảnh về (28, 28)
    #     im_resize = cv2.resize(im_crop, (28, 28), interpolation=cv2.INTER_AREA)
    #     im_resize = np.reshape(im_resize, (28, 28, 1))  # Chuyển thành dạng tensor
    
    #     train_data.append(im_resize)    


In [35]:
s=''
for i in range(len(train_data)):
    train_data[i]=np.array(train_data[i])
    train_data[i]=train_data[i].reshape(1,45,45,1)
    result = np.argmax(loaded_model.predict(train_data[i]), axis=-1)
    result=np.argmax(loaded_model.predict(train_data[i]), axis=-1)
    if(result[0]==10):
        print("-")
        s=s+'-'
    if(result[0]==11):
        print("+")
        s=s+'+'
    if(result[0]==12):
        print("*")
        s=s+'*'
    if(result[0]==0):
        print("0")
        s=s+'0'
    if(result[0]==1):
        print("1")
        s=s+'1'
    if(result[0]==2):
        print("2")
        s=s+'2'
    if(result[0]==3):
        print("3")
        s=s+'3'
    if(result[0]==4):
        print("4")
        s=s+'4'
    if(result[0]==5):
        print("5")
        s=s+'5'
    if(result[0]==6):
        print("6")
        s=s+'6'
    if(result[0]==7):
        print("7")
        s=s+'7'
    if(result[0]==8):
        print("8")
        s=s+'8'
    if(result[0]==9):
        print("9")  
        s=s+'9'

print(s)
try:
    result = eval(s)  # Tính toán chuỗi biểu thức
    print("Kết quả:", result)
except Exception as e:
    print("Lỗi tính toán:", e)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 151ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
8
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
7
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step
-
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
3
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
3
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step
0
871-330
Kết quả: 541


## Our Model was successfully Tested 

# Thank You !

In [36]:
labels = {
    0: '0', 1: '1', 2: '2', 3: '3', 4: '4',
    5: '5', 6: '6', 7: '7', 8: '8', 9: '9',
    10: '-', 11: '+', 12: '*'
}

for i in range(len(train_data)):
    train_data[i] = np.array(train_data[i]).reshape(1, 45, 45, 1)

    # Dự đoán xác suất
    probs = loaded_model.predict(train_data[i])[0]

    # Lấy top 3 nhãn có xác suất cao nhất
    top3_indices = probs.argsort()[-3:][::-1]  # Sắp xếp giảm dần
    top3_labels = [(labels[idx], probs[idx]) for idx in top3_indices]

    print(f"Ảnh {i+1}:")
    for label, prob in top3_labels:
        print(f"  → {label} với xác suất {prob:.4f}")
    print()


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step
Ảnh 1:
  → 8 với xác suất 1.0000
  → 6 với xác suất 0.0000
  → 5 với xác suất 0.0000

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
Ảnh 2:
  → 7 với xác suất 0.9974
  → + với xác suất 0.0016
  → 2 với xác suất 0.0009

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step
Ảnh 3:
  → 1 với xác suất 0.9987
  → 4 với xác suất 0.0011
  → 9 với xác suất 0.0002

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
Ảnh 4:
  → - với xác suất 0.9454
  → + với xác suất 0.0543
  → 7 với xác suất 0.0003

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
Ảnh 5:
  → 3 với xác suất 0.9999
  → 5 với xác suất 0.0001
  → 8 với xác suất 0.0000

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step
Ảnh 6:
  → 3 với xác suất 0.9978
  → 5 với xác suất 0.0020
  → 6 với xác suất 0.0000

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step
Ảnh 7:
  → 0 với xác suất 0.9983
  → 5 với xác suất 0.0015
  → 9 với xác suất 0.0001

